# Change these first
owner: MITPAcademy
repo: status.mitpa.tech

sites:
  - name: MITPA Site
    url: https://mitpa.tech
  - name: MITPA CDN
    url: https://cdn.mitpa.tech

status-website:
  cname: status.mitpa.tech
  logoUrl: https://camo.githubusercontent.com/7c6861abe08e7c71bb01829c681be8b8678d35bd89dc3d61d14f781b9ec947d6/68747470733a2f2f6d697470612d746563682e76657263656c2e6170702f4c6f676f2e706e67
  name: MITPA Status
  introTitle: "**MITPA Status Page**"
  introMessage: Real-time monitoring of our services, powered by GitHub Actions. Transparency and reliability for our community.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/MITPAcademy/status.mitpa.tech
